import { describe,expect,it } from 'vitest';
import { advanceGame, evaluateWinner, generatePrompt, submitAction } from '../src/game/engine';
import { gameAt } from './helpers';

const act=(kind:any,targetSeat?:number,extra:object={})=>({kind,targetSeat,matched:`${kind}`, ...extra});
describe('规则引擎',()=>{
  it('首轮平票进入 PK，再次平票无人出局',()=>{const g=gameAt('day_vote');g.players.forEach((p,i)=>submitAction(g,p.id,i===6?act('vote',undefined,{abstain:true}):act('vote',i%2?1:2)));advanceGame(g);expect(g.phase).toBe('runoff_speech');expect(g.runoffSeats.sort()).toEqual([1,2]);g.phase='runoff_vote';g.players.forEach((p,i)=>submitAction(g,p.id,i===6?act('vote',undefined,{abstain:true}):act('vote',i%2?1:2)));advanceGame(g);expect(g.players.every(p=>p.alive)).toBe(true);expect(g.phase).toBe('night_wolf');expect(g.day).toBe(2);});
  it('女巫用药会消费药物，且同一阶段不能提交第二次',()=>{const g=gameAt('night_witch');g.currentNight.wolfTarget=1;const witch=g.players.find(p=>p.role==='witch')!;submitAction(g,witch.id,act('antidote',1));expect(g.witch.antidoteAvailable).toBe(false);expect(()=>submitAction(g,witch.id,act('poison',2))).toThrow('本阶段已提交');});
  it('猎人仅在狼刀或放逐后可开枪，毒死不能开枪',()=>{const wolfKilled=gameAt('dawn'),hunter=wolfKilled.players.find(p=>p.role==='hunter')!;hunter.alive=false;hunter.deathCause='wolf';wolfKilled.currentNight.deaths=[hunter.seat];advanceGame(wolfKilled);expect(wolfKilled.phase).toBe('last_words');wolfKilled.phase='last_words';submitAction(wolfKilled,hunter.id,act('last_words',undefined,{text:'再见'}));advanceGame(wolfKilled);expect(wolfKilled.phase).toBe('hunter_action');const poisoned=gameAt('dawn'),h2=poisoned.players.find(p=>p.role==='hunter')!;h2.alive=false;h2.deathCause='poison';poisoned.currentNight.deaths=[h2.seat];advanceGame(poisoned);expect(poisoned.phase).toBe('last_words');poisoned.phase='last_words';submitAction(poisoned,h2.id,act('last_words',undefined,{text:'再见'}));advanceGame(poisoned);expect(poisoned.phase).toBe('day_speech');});
  it('即使猎人死亡造成狼人数达成屠边条件，也先允许猎人开枪',()=>{const g=gameAt('dawn'),hunter=g.players.find(p=>p.role==='hunter')!;g.players.filter(p=>p.role==='villager').forEach(p=>p.alive=false);hunter.alive=false;hunter.deathCause='wolf';g.currentNight.deaths=[hunter.seat];g.config.nightDeathLastWords=false;advanceGame(g);expect(evaluateWinner(g)).toBe('wolves');expect(g.phase).toBe('hunter_action');});
  it('判断狼人全灭与狼人数量达到好人数量',()=>{const good=gameAt('day_speech');good.players.filter(p=>p.role==='wolf').forEach(p=>p.alive=false);expect(evaluateWinner(good)).toBe('good');const wolves=gameAt('day_speech');wolves.players.filter(p=>p.role!=='wolf').slice(0,3).forEach(p=>p.alive=false);expect(evaluateWinner(wolves)).toBe('wolves');});
  it('死亡玩家不能行动',()=>{const g=gameAt('day_vote'),p=g.players[0];p.alive=false;expect(()=>submitAction(g,p.id,act('vote',2))).toThrow('死亡玩家不能行动');});
  it('Prompt 不泄露其他玩家身份或私密查验',()=>{const g=gameAt('day_speech');const villager=g.players.find(p=>p.role==='villager')!,seer=g.players.find(p=>p.role==='seer')!,wolf=g.players.find(p=>p.role==='wolf')!;g.actions.push({id:'secret',day:1,phase:'night_seer',playerId:seer.id,action:act('inspect',wolf.seat),raw:'',timestamp:new Date().toISOString(),result:`${wolf.seat}号是狼人`});const prompt=generatePrompt(g,villager.id);expect(prompt).not.toContain(`${wolf.seat}号是狼人`);expect(prompt).not.toContain('你的狼队友');expect(prompt).not.toContain('女巫用药');});
});
